

services:
  webapp:
    build: .
    # command:
    ports:
       - 80:80
    volumes:
      - laravel-vol:/var/www/html/storage
    # environment:
    depends_on:
      - mysql

  mysql:
    image:  mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=diaa
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-vol:/var/lib/mysql
    ports:
      - 3306:3306


volumes:
  laravel-vol:
  mysql-vol:
      

